[package]
name = "vehje-syntax"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vehje-ir.workspace = true
vehje-lex.workspace = true
hilavitkutin-api.workspace = true
notko.workspace = true

[dev-dependencies]
arvo.workspace = true


[features]
default = []
