[package]
name = "vehje-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vehje-ir.workspace = true
vehje-typecheck.workspace = true
hilavitkutin-api.workspace = true
notko.workspace = true

[dev-dependencies]
arvo.workspace = true

[features]
default = []
