[package]
name = "vehje-ir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arvo.workspace = true
notko.workspace = true
hilavitkutin-api.workspace = true
hilavitkutin-str.workspace = true

[build-dependencies]
mockspace.workspace = true

[features]
default = []
