[package]
name = "vehje"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vehje-ir.workspace = true
vehje-signature.workspace = true
vehje-resolve.workspace = true
vehje-typecheck.workspace = true
vehje-lower.workspace = true
vehje-codegen.workspace = true
vehje-runtime-gen.workspace = true
vehje-runtime-driver.workspace = true
hilavitkutin-api.workspace = true
hilavitkutin-str.workspace = true
notko.workspace = true

[dev-dependencies]
arvo.workspace = true
arvo-bits.workspace = true

[build-dependencies]
mockspace.workspace = true

[features]
default = []
