[package]
name = "vehje-lower"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arvo.workspace = true
notko.workspace = true
vehje-ir.workspace = true
vehje-fixpoint.workspace = true

[build-dependencies]
mockspace.workspace = true

[dev-dependencies]
hilavitkutin-str.workspace = true
arvo-bits.workspace = true

[features]
default = []
