[package]
name = "vehje-runtime-tests"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
vehje-runtime-abi.workspace = true
vehje-runtime-driver.workspace = true
hilavitkutin-api.workspace = true
notko.workspace = true

[dev-dependencies]
arvo.workspace = true

[build-dependencies]
mockspace.workspace = true

[features]
default = ["std"]
std = []
