[workspace]
[package]
name = "carrier_vertical_leaf_vert8"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
name = "carrier_vertical_leaf_vert8"
path = "src/lib.rs"
crate-type = ["cdylib"]
[dependencies]
mockspace-bench-core = { git = "https://github.com/hiisi-digital/mockspace", rev = "8c5f87ae1a916c45b40c6ea690dc42402f91d199", features = ["std"] }
mockspace-bench-macro = { git = "https://github.com/hiisi-digital/mockspace", rev = "8c5f87ae1a916c45b40c6ea690dc42402f91d199" }
mockspace-bench-matrix = { git = "https://github.com/hiisi-digital/mockspace", rev = "8c5f87ae1a916c45b40c6ea690dc42402f91d199", default-features = false }
vehje-bench-carrier = { path = "../../carrier", features = ["vertical"] }
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
