#!/usr/bin/env python3
"""Generate the resolve name-resolution bench: one variant cdylib per lookup
strategy, all resolving the identical reference stream to identical (depth,slot)
binders, differing only in the lookup mechanism. Audit-fixed replacement for the
standalone `resolve-name-scope/resolve.zig`, which (a) ran outside the harness
with a hand-timed loop and a header-only CSV, and (b) had each earlier hx_resolve
port rebuild its table INSIDE the timed region and, worse, produce a DIFFERENT
binder packing per variant (flat returned the bare name, linear returned a packed
depth/slot), so the variants were not cross-validatable.

The fix, structurally:
  - The scope structure and the reference stream are built ONCE per process via
    OnceLock (runtime state behind a pointer, so the resolution cannot be
    const-folded), never inside the timed region.
  - The reference index is folded with the FFI input byte, so the resolution
    cannot be hoisted or precomputed.
  - Every strategy resolves each reference to the byte-identical binder
    ((DEPTH-1-d) << 8) | slot, so the harness cross-validation catches a wrong
    strategy.

Strategies (the design fork):
  resolve_flat    flat shadow-stack symbol table: one open-addressed hash
                  name -> current binder. O(1) per reference. The baseline and
                  the expected winner.
  resolve_hashed  hashed-per-scope: walk enclosing scopes innermost-out,
                  hash-lookup within each. O(depth).
  resolve_linear  linear scope-chain walk: walk scopes innermost-out,
                  linear-scan each scope's name list. O(depth * width).

Run: python3 gen_resolve_name_scope.py && for v in resolve_flat resolve_hashed \
  resolve_linear; do (cd variants/$v && cargo build --release); done
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SIZES = [64, 256, 1024, 4096, 16384]
BASELINE = "resolve_flat"
SEED = "0x5eed_a11c_0503_0001"
VARIANTS = ["resolve_flat", "resolve_hashed", "resolve_linear"]

CARGO = """\
[workspace]
[package]
name = "{name}"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
name = "{name}"
path = "src/lib.rs"
crate-type = ["cdylib"]
[dependencies]
mockspace-bench-core = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev", features = ["std"] }}
mockspace-bench-macro = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev" }}
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
"""

# Shared prelude: identical in every variant. The reference stream and the size
# assertions the finding names. The reference stream biases 60% to the innermost
# three scopes (the local-heavy real shape), matching the original bench.
PRELUDE = """\
// AUTO-GENERATED by gen_resolve_name_scope.py. Name-resolution axis, strategy =
// {strat}. Every strategy resolves the identical reference stream to identical
// (depth, slot) binders; the harness cross-validates byte-identical output. The
// scope structure and the reference stream are built once per process via
// OnceLock (runtime state, not a const), and the reference index is folded with
// the FFI input byte so the resolution cannot be hoisted.
use mockspace_bench_core::{{timed, FfiBenchCall}};
use mockspace_bench_macro::bench_variant;
use std::sync::OnceLock;

const DEPTH: usize = 12;
const WIDTH: usize = 8;
const REFS_LEN: usize = 4096;
// the layout the finding names: 12 nested scopes x 8 bindings, power-of-two ref stream.
const _: () = assert!(DEPTH == 12 && WIDTH == 8 && REFS_LEN.is_power_of_two());

static REFS: OnceLock<Vec<u32>> = OnceLock::new();
fn build_refs() -> Vec<u32> {{
    let mut v = Vec::with_capacity(REFS_LEN);
    let mut s: u64 = 9;
    for _ in 0..REFS_LEN {{
        s = s.wrapping_mul(6364136223846793005).wrapping_add(1);
        let d: usize = if (s >> 40) % 10 < 6 {{
            DEPTH - 1 - ((s >> 30) as usize % 3) // 60%: innermost three scopes
        }} else {{
            (s >> 20) as usize % DEPTH
        }};
        let i = (s >> 10) as usize % WIDTH;
        v.push((d * WIDTH + i) as u32);
    }}
    v
}}
"""

# Per-strategy: the OnceLock structure + its builder, the get_or_init line, and
# the resolve expression yielding the packed binder ((DEPTH-1-d) << 8) | slot.
FLAT = {
    "struct": """\
const FLAT_CAP: usize = 512;
static FLAT: OnceLock<Vec<(u32, u32)>> = OnceLock::new(); // (name, binder), open-addressed, u32::MAX = empty
fn build_flat() -> Vec<(u32, u32)> {
    let mut t = vec![(u32::MAX, 0u32); FLAT_CAP];
    for d in 0..DEPTH {
        for i in 0..WIDTH {
            let nm = (d * WIDTH + i) as u32;
            let binder = (((DEPTH - 1 - d) as u32) << 8) | i as u32;
            let mut h = (nm.wrapping_mul(2654435761) as usize) & (FLAT_CAP - 1);
            while t[h].0 != u32::MAX {
                h = (h + 1) & (FLAT_CAP - 1);
            }
            t[h] = (nm, binder);
        }
    }
    t
}
""",
    "init": "    let flat = FLAT.get_or_init(build_flat);",
    "resolve": """{
                let mut h = (nm.wrapping_mul(2654435761) as usize) & (FLAT_CAP - 1);
                loop {
                    let (k, bd) = flat[h];
                    if k == nm {
                        break bd;
                    }
                    if k == u32::MAX {
                        break 0xffff;
                    }
                    h = (h + 1) & (FLAT_CAP - 1);
                }
            }""",
}
HASHED = {
    "struct": """\
const HW: usize = WIDTH * 2; // per-scope hash size (16), power of two
static HSCOPES: OnceLock<Vec<[(u32, u16); HW]>> = OnceLock::new();
fn build_hscopes() -> Vec<[(u32, u16); HW]> {
    let mut v = Vec::with_capacity(DEPTH);
    for d in 0..DEPTH {
        let mut sc = [(u32::MAX, 0u16); HW];
        for i in 0..WIDTH {
            let nm = (d * WIDTH + i) as u32;
            let mut h = (nm.wrapping_mul(2654435761) as usize) & (HW - 1);
            while sc[h].0 != u32::MAX {
                h = (h + 1) & (HW - 1);
            }
            sc[h] = (nm, i as u16);
        }
        v.push(sc);
    }
    v
}
""",
    "init": "    let hscopes = HSCOPES.get_or_init(build_hscopes);",
    "resolve": """{
                let mut d = DEPTH - 1;
                loop {
                    let sc = &hscopes[d];
                    let mut h = (nm.wrapping_mul(2654435761) as usize) & (HW - 1);
                    let mut r = u32::MAX;
                    let mut p = 0;
                    while p < HW {
                        let (k, slot) = sc[h];
                        if k == nm {
                            r = (((DEPTH - 1 - d) as u32) << 8) | slot as u32;
                            break;
                        }
                        if k == u32::MAX {
                            break;
                        }
                        h = (h + 1) & (HW - 1);
                        p += 1;
                    }
                    if r != u32::MAX {
                        break r;
                    }
                    if d == 0 {
                        break 0xffff;
                    }
                    d -= 1;
                }
            }""",
}
LINEAR = {
    "struct": """\
static SCOPES: OnceLock<Vec<[u32; WIDTH]>> = OnceLock::new();
fn build_scopes() -> Vec<[u32; WIDTH]> {
    let mut v = Vec::with_capacity(DEPTH);
    for d in 0..DEPTH {
        let mut sc = [0u32; WIDTH];
        for i in 0..WIDTH {
            sc[i] = (d * WIDTH + i) as u32;
        }
        v.push(sc);
    }
    v
}
""",
    "init": "    let scopes = SCOPES.get_or_init(build_scopes);",
    "resolve": """{
                let mut d = DEPTH - 1;
                loop {
                    let sc = &scopes[d];
                    let mut r = u32::MAX;
                    let mut i = 0;
                    while i < WIDTH {
                        if sc[i] == nm {
                            r = (((DEPTH - 1 - d) as u32) << 8) | i as u32;
                            break;
                        }
                        i += 1;
                    }
                    if r != u32::MAX {
                        break r;
                    }
                    if d == 0 {
                        break 0xffff;
                    }
                    d -= 1;
                }
            }""",
}

STRATS = {"resolve_flat": FLAT, "resolve_hashed": HASHED, "resolve_linear": LINEAR}


def strat_tag(name):
    return {"resolve_flat": "flat shadow-stack", "resolve_hashed": "hashed-per-scope",
            "resolve_linear": "linear scope-chain"}[name]


LIB_TMPL = """\
{prelude}
{struct}
#[bench_variant("{name}", sizes = [64, 256, 1024, 4096, 16384])]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    let refs = REFS.get_or_init(build_refs);
{init}
    timed! {{ run {{
        let mut acc: u64 = 0;
        for (k, &b) in input.iter().enumerate() {{
            let nm = refs[(k ^ b as usize) & (REFS_LEN - 1)];
            let binder = {resolve};
            acc ^= binder as u64;
        }}
        output.copy_from_slice(&acc.to_le_bytes());
    }} }}
}}
"""


def write_variant(name):
    st = STRATS[name]
    d = os.path.join(HERE, "variants", name, "src")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(HERE, "variants", name, "Cargo.toml"), "w") as f:
        f.write(CARGO.format(name=name))
    lib = LIB_TMPL.format(
        prelude=PRELUDE.format(strat=strat_tag(name)),
        struct=st["struct"],
        name=name,
        init=st["init"],
        resolve=st["resolve"],
    )
    with open(os.path.join(d, "lib.rs"), "w") as f:
        f.write(lib)
    return name


def bench_section():
    paths = ", ".join(f'"variants/{n}/target/release/{n}"' for n in VARIANTS)
    out = [
        "[bench.resolve_name_scope]",
        'title = "Name resolution: flat shadow-stack vs hashed-per-scope vs linear scope-chain walk"',
        'workload = "realistic"',
        f"master_seed = {SEED}",
        "[bench.resolve_name_scope.normalise]",
        f'baseline = "{BASELINE}"',
        'mode = "subtract"',
    ]
    for n in SIZES:
        out.append("[[bench.resolve_name_scope.sizes]]")
        out.append(f"n = {n}")
        out.append(f"variants = [{paths}]")
    return "\n".join(out) + "\n"


def main():
    for n in VARIANTS:
        write_variant(n)
    frag_dir = os.path.join(HERE, "carrier_fragments")
    os.makedirs(frag_dir, exist_ok=True)
    frag = os.path.join(frag_dir, "resolve_interner_project.toml")
    marker = "# >>> resolve_name_scope (generated)"
    prior = ""
    if os.path.exists(frag):
        prior = open(frag).read()
        if marker in prior:
            prior = prior.split(marker)[0].rstrip() + "\n"
    with open(frag, "w") as f:
        f.write(prior.rstrip() + ("\n\n" if prior.strip() else "") + marker + "\n" + bench_section())
    print("generated variants:", ", ".join(VARIANTS))
    print("wrote [bench.resolve_name_scope] to carrier_fragments/resolve_interner_project.toml")


if __name__ == "__main__":
    main()
