#!/usr/bin/env python3
"""Generate the runtime-string interning bench: should a CONSTRUCTED string be
interned by default?

`interner-intern-hotpath` measured the COMPILE-side interner (identifiers and
literals during lexing) at ~19 ns per token and found it string-hash-bound and not
a bottleneck. That population is small, heavily repeated, and fully known before
anything runs. A running program's strings are a different population: built by
concatenation and interpolation, frequently unique, frequently short-lived. So the
compile-side number does not transfer, and `dedup-vs-reuse` explicitly refused to
let its record verdict transfer either, since a short string is far cheaper to hash
than a sixteen-field record and is compared more often.

Interning a constructed string pays a hash of its bytes at construction to buy an
identity comparison later. That is a good trade when strings are compared often and
built rarely, and a bad one when the reverse holds, which is the templating and
config norm. The construct-to-compare ratio is therefore the axis, and it is what
these two benches sweep.

Three strategies, byte-identical output required (the harness cross-validates, so a
strategy whose equality verdicts diverge is rejected rather than timed):
  plain   copy the bytes; equality is a byte comparison.
  eager   copy the bytes, then hash and intern immediately; equality is an id
          comparison. Every construction pays the hash whether or not it is ever
          compared.
  lazy    copy the bytes and leave the string un-interned; intern on FIRST
          comparison and memoise the id on the handle. Construction stays free and
          only strings that actually get compared pay the hash. The middle option
          that a construct-heavy workload should favour, and the one a design that
          jumped straight to "intern everything" would never have considered.

Three benches. The first two vary how often a built string is compared; the third
exists to remove a bias the first two carry.
  str_compare_light  1 comparison per construction. The templating norm: build
                     strings, emit them, rarely compare them.
  str_compare_heavy  8 comparisons per construction, strings usually differing.
  str_compare_equal  8 comparisons per construction of EQUAL strings (GROUP=8 makes
                     consecutive iterations build the identical string). The first
                     two let the byte comparison exit on the first differing byte,
                     which flatters `plain` and would have measured early-exit rather
                     than the interning question. This regime removes that advantage
                     and is interning's genuine best case.

Run: python3 gen_string_interning.py && for v in str_l_plain str_l_eager \\
  str_l_lazy str_h_plain str_h_eager str_h_lazy str_e_plain str_e_eager \\
  str_e_lazy; do (cd variants/$v && cargo build --release); done
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SIZES = [64, 256, 1024, 4096, 16384]
SEED_L = "0x5eed_57a1_0725_0011"
SEED_H = "0x5eed_57a1_0725_0012"
SEED_E = "0x5eed_57a1_0725_0013"

CARGO = """\
[workspace]
[package]
name = "{name}"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
name = "{name}"
path = "src/lib.rs"
crate-type = ["cdylib"]
[dependencies]
mockspace-bench-core = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev", features = ["std"] }}
mockspace-bench-macro = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev" }}
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
"""

PLAIN = """\
                let cur = sc.build(base, tag);
                for _ in 0..COMPARES {
                    if sc.bytes_eq(cur, prev) { acc ^= 1; }
                }
                prev = cur;"""

EAGER = """\
                let mut cur = sc.build(base, tag);
                sc.intern(&mut cur);
                for _ in 0..COMPARES {
                    if cur.id == prev.id { acc ^= 1; }
                }
                prev = cur;"""

LAZY = """\
                let mut cur = sc.build(base, tag);
                for _ in 0..COMPARES {
                    // pay the hash only for a string that is actually compared,
                    // and only once: the id memoises on the handle.
                    if cur.id == NOID { sc.intern(&mut cur); }
                    if prev.id == NOID { sc.intern(&mut prev); }
                    if cur.id == prev.id { acc ^= 1; }
                }
                prev = cur;"""

LIB_TMPL = """\
// AUTO-GENERATED by gen_string_interning.py. Runtime-string interning axis:
// {compares} comparison(s) per construction, strategy = {strat}. Within a bench
// every strategy returns the byte-identical accumulator; the harness cross-validates
// output, which is what proves the id comparison and the byte comparison agree. The
// byte arena and intern table are allocated once per process and cleared outside the
// timed region; the base word and the tag are folded with the FFI input byte so no
// construction can be hoisted.
#![allow(dead_code, unused_mut)]
use mockspace_bench_core::{{timed, FfiBenchCall}};
use mockspace_bench_macro::bench_variant;
use std::cell::RefCell;

const NBASE: usize = 64; // distinct base words: a duplicate-rich population
const NTAG: usize = 16; // distinct suffixes, so ~1024 distinct strings recur
const COMPARES: usize = {compares};
const GROUP: usize = {group}; // consecutive iterations sharing one string
const ARENA: usize = 16384 * 40 + 64;
const TSIZE: usize = 1 << 16;
const EMPTY: u32 = u32::MAX;
const NOID: u32 = u32::MAX;

/// A string handle: a span in the byte arena plus a memoised interned id
/// (`NOID` until interned). One shape serves all three strategies so the
/// comparison is between policies, not between representations.
#[derive(Clone, Copy)]
struct Sref {{
    off: u32,
    len: u32,
    id: u32,
}}

struct Scratch {{
    bytes: Vec<u8>,
    slots: Vec<u32>, // table slot -> index into `strs`
    strs: Vec<Sref>, // the interned population, id = index here
    top: usize,
}}

impl Scratch {{
    fn new() -> Self {{
        Self {{
            bytes: vec![0u8; ARENA],
            slots: vec![EMPTY; TSIZE],
            strs: Vec::with_capacity(1 << 14),
            top: 0,
        }}
    }}
    fn reset(&mut self) {{
        self.top = 0;
        self.strs.clear();
        self.slots.iter_mut().for_each(|s| *s = EMPTY);
    }}
    /// Build a string by concatenating a base word with a numeric tag, which is
    /// what interpolation actually does.
    #[inline(always)]
    fn build(&mut self, base: &[u8], tag: usize) -> Sref {{
        let off = self.top;
        self.bytes[off..off + base.len()].copy_from_slice(base);
        let mut n = off + base.len();
        let mut t = tag;
        loop {{
            self.bytes[n] = b'0' + (t % 10) as u8;
            n += 1;
            t /= 10;
            if t == 0 {{
                break;
            }}
        }}
        self.top = n;
        Sref {{ off: off as u32, len: (n - off) as u32, id: NOID }}
    }}
    #[inline(always)]
    fn slice(&self, s: Sref) -> &[u8] {{
        &self.bytes[s.off as usize..(s.off + s.len) as usize]
    }}
    #[inline(always)]
    fn bytes_eq(&self, a: Sref, b: Sref) -> bool {{
        self.slice(a) == self.slice(b)
    }}
    /// Hash the bytes, then insert or return the existing id. Memoises onto the
    /// handle so a repeat intern of the same handle is free.
    #[inline(always)]
    fn intern(&mut self, s: &mut Sref) {{
        let mut h: u64 = 0xcbf2_9ce4_8422_2325;
        for b in self.slice(*s) {{
            h ^= *b as u64;
            h = h.wrapping_mul(0x0000_0100_0000_01b3);
        }}
        let mut i = (h as usize) & (TSIZE - 1);
        loop {{
            let slot = self.slots[i];
            if slot == EMPTY {{
                let id = self.strs.len() as u32;
                self.strs.push(*s);
                self.slots[i] = id;
                s.id = id;
                return;
            }}
            let cand = self.strs[slot as usize];
            if self.slice(cand) == self.slice(*s) {{
                s.id = slot;
                return;
            }}
            i = (i + 1) & (TSIZE - 1);
        }}
    }}
}}

thread_local! {{
    static SCRATCH: RefCell<Scratch> = RefCell::new(Scratch::new());
    static BASES: Vec<Vec<u8>> = {{
        let mut v = Vec::with_capacity(NBASE);
        for k in 0..NBASE {{
            // 20-byte word-like bases: the realistic short-string regime
            let mut w = Vec::with_capacity(24);
            for j in 0..20 {{
                w.push(b'a' + ((k * 7 + j * 3) % 26) as u8);
            }}
            v.push(w);
        }}
        v
    }};
}}

#[bench_variant("{name}", sizes = [64, 256, 1024, 4096, 16384])]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    BASES.with(|bases| {{
        SCRATCH.with(|cell| {{
            let mut sc = cell.borrow_mut();
            let sc = &mut *sc;
            sc.reset(); // untimed: arena and table start clean every call
            timed! {{ run {{
                let mut acc: u64 = 0;
                let mut prev = sc.build(&bases[0], 0);
                for (k, _b) in input.iter().enumerate() {{
                    // the group's leading input byte keeps the construction data-dependent
                    // (so nothing hoists) while staying constant across a group, which is
                    // what makes the strings within a group identical.
                    let gb = input[(k / GROUP) * GROUP] as usize;
                    let gi = (k / GROUP) ^ gb;
                    let base = &bases[gi % NBASE];
                    let tag = gi.wrapping_mul(31) % NTAG;
{body}
                }}
                acc ^= prev.len as u64;
                output.copy_from_slice(&acc.to_le_bytes());
            }} }}
        }})
    }})
}}
"""

VARIANTS = [
    ("plain", "byte comparison, never interned", PLAIN),
    ("eager", "intern at construction, id comparison", EAGER),
    ("lazy", "intern on first comparison, id comparison", LAZY),
]


def write_variant(name, strat_tag, body, compares, group):
    d = os.path.join(HERE, "variants", name, "src")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(HERE, "variants", name, "Cargo.toml"), "w") as f:
        f.write(CARGO.format(name=name))
    with open(os.path.join(d, "lib.rs"), "w") as f:
        f.write(LIB_TMPL.format(name=name, strat=strat_tag, body=body, compares=compares, group=group))
    return name


def bench_section(bench, title, baseline, seed, names):
    paths = ", ".join(f'"variants/{n}/target/release/{n}"' for n in names)
    out = [
        f"[bench.{bench}]",
        f'title = "{title}"',
        'workload = "realistic"',
        f"master_seed = {seed}",
        f"[bench.{bench}.normalise]",
        f'baseline = "{baseline}"',
        'mode = "subtract"',
    ]
    for n in SIZES:
        out.append(f"[[bench.{bench}.sizes]]")
        out.append(f"n = {n}")
        out.append(f"variants = [{paths}]")
    return "\n".join(out) + "\n"


def main():
    l_names = [write_variant(f"str_l_{n}", t, b, 1, 1) for n, t, b in VARIANTS]
    h_names = [write_variant(f"str_h_{n}", t, b, 8, 1) for n, t, b in VARIANTS]
    e_names = [write_variant(f"str_e_{n}", t, b, 8, 8, ) for n, t, b in VARIANTS]
    sec = (
        bench_section(
            "str_compare_light",
            "Runtime string interning, 1 compare per build: the templating norm",
            "str_l_plain", SEED_L, l_names)
        + "\n"
        + bench_section(
            "str_compare_heavy",
            "Runtime string interning, 8 compares per build: interning's best case",
            "str_h_plain", SEED_H, h_names)
        + "\n"
        + bench_section(
            "str_compare_equal",
            "Runtime string interning, 8 compares of EQUAL strings: byte compare cannot exit early",
            "str_e_plain", SEED_E, e_names)
    )
    frag_dir = os.path.join(HERE, "carrier_fragments")
    os.makedirs(frag_dir, exist_ok=True)
    with open(os.path.join(frag_dir, "string_interning.toml"), "w") as f:
        f.write("# >>> string_interning (generated)\n" + sec)
    print("generated variants:", ", ".join(l_names + h_names + e_names))
    print("wrote str_compare_{light,heavy,equal} to carrier_fragments/string_interning.toml")


if __name__ == "__main__":
    main()
