#!/usr/bin/env python3
"""Generate the carrier dispatch bench: switch versus function-pointer-table
dispatch, at two op-vocabulary sizes. The audit-relevant point (Wingo) is that
"switch beats tail-threading" from the old bench was a toolchain verdict over a
tiny random three-op stream, and the switch's advantage narrows as the op
vocabulary grows. This bench measures the honest Rust comparison (switch vs an
indirect-threaded function-pointer table) and sweeps vocabulary to show the
regime dependence. The guaranteed-tail-call ("threaded") shape Deegen relies on
is not expressible in Rust; it is a Zig cdylib follow-up that consumes identical
program bytes, which is one of the three places the shipped language is
load-bearing.

Run: python3 gen_carrier_dispatch.py && for v in carrier_disp_switch_v4 \
  carrier_disp_fntable_v4 carrier_disp_switch_v17 carrier_disp_fntable_v17; do \
  (cd variants/$v && cargo build --release); done && cargo build --release && \
  ./target/release/vehje-benches carrier_dispatch_v4 && \
  ./target/release/vehje-benches carrier_dispatch_v17
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SIZES = [64, 256, 1024, 4096, 16384]
SEED = "0x5eed_d15b_a7c4_0002"
# (vocab_tag, vocab_value): the two op-vocabularies to compare.
VOCABS = [("v4", 4), ("v17", 17)]
# (shape_tag, carrier fn): the dispatch shapes under test.
SHAPES = [("switch", "interpret"), ("fntable", "interpret_fntable")]

CARGO = """\
[workspace]
[package]
name = "{name}"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
name = "{name}"
path = "src/lib.rs"
crate-type = ["cdylib"]
[dependencies]
mockspace-bench-core = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev", features = ["std"] }}
mockspace-bench-macro = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev" }}
vehje-bench-carrier = {{ path = "../../carrier" }}
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
"""

LIB = """\
// AUTO-GENERATED by gen_carrier_dispatch.py. Dispatch-shape axis variant:
// {shape} dispatch over a program drawn from an op vocabulary of {vocab}. Only
// the dispatch function differs across a bench's variants; the program, layout,
// and everything else are held fixed. The program crosses FFI as bytes.
use mockspace_bench_core::{{timed, FfiBenchCall}};
use mockspace_bench_macro::bench_variant;
use std::sync::OnceLock;
use vehje_bench_carrier::{{{fn_name}, program_vocab, Decoded, REC24}};

static BYTES: OnceLock<Vec<u8>> = OnceLock::new();
const ITERS: usize = 16;
const VOCAB: u8 = {vocab};

#[bench_variant("{name}", sizes = [64, 256, 1024, 4096, 16384])]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    let bytes = BYTES.get_or_init(|| program_vocab(N, VOCAB, REC24));
    let d = Decoded::parse(bytes, REC24).unwrap();
    let mut results = vec![0u64; d.node_count];
    timed! {{ run {{
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < ITERS {{
            acc ^= {fn_name}(&d, input[k % N] as u64 ^ (k as u64), &mut results);
            k += 1;
        }}
        output.copy_from_slice(&acc.to_le_bytes());
    }} }}
}}
"""


def variant(vocab_tag, vocab_val, shape_tag, fn_name):
    name = f"carrier_disp_{shape_tag}_{vocab_tag}"
    d = os.path.join(HERE, "variants", name, "src")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(HERE, "variants", name, "Cargo.toml"), "w") as f:
        f.write(CARGO.format(name=name))
    with open(os.path.join(d, "lib.rs"), "w") as f:
        f.write(LIB.format(name=name, shape=shape_tag, vocab=vocab_val, fn_name=fn_name))
    return name


def bench_section(vocab_tag, names):
    bench = f"carrier_dispatch_{vocab_tag}"
    baseline = [n for n in names if "switch" in n][0]
    paths = ", ".join(f'"variants/{n}/target/release/{n}"' for n in names)
    out = [
        f"[bench.{bench}]",
        f'title = "Dispatch shape: switch vs fn-pointer table, op vocab {vocab_tag} (carrier)"',
        'workload = "realistic"',
        f"master_seed = {SEED}",
        f"[bench.{bench}.normalise]",
        f'baseline = "{baseline}"',
        'mode = "subtract"',
    ]
    for n in SIZES:
        out.append(f"[[bench.{bench}.sizes]]")
        out.append(f"n = {n}")
        out.append(f"variants = [{paths}]")
    return "\n".join(out) + "\n"


def main():
    made, sections = [], []
    for vt, vv in VOCABS:
        names = [variant(vt, vv, st, fn) for st, fn in SHAPES]
        made += names
        sections.append(bench_section(vt, names))
    marker = "# >>> carrier_dispatch (generated)"
    toml_path = os.path.join(HERE, "bench.toml")
    with open(toml_path) as f:
        toml = f.read()
    if marker in toml:
        toml = toml.split(marker)[0].rstrip() + "\n"
    with open(toml_path, "w") as f:
        f.write(toml.rstrip() + "\n\n" + marker + "\n" + "\n".join(sections))
    print("generated variants:", ", ".join(made))
    print("appended carrier_dispatch_v4, carrier_dispatch_v17 to bench.toml")


if __name__ == "__main__":
    main()
