#!/usr/bin/env python3
"""Generate the interner intern-hot-path bench: one variant cdylib per
(hash function x load factor) cell, all interning the identical token stream to
the identical id sequence, differing only in the string-hash and the table load
factor. Audit-fixed replacement for `interner-intern-hotpath/intern.zig`, which
ran outside the harness with a hand-timed loop and a header-only CSV, and whose
"~75%" load-factor label was actually ~100% (CAP == DISTINCT).

The fix, structurally:
  - The token corpus (4096 distinct 3..11-byte identifiers) and the parse-
    realistic access stream (70% hitting the top-64 common tokens) are built ONCE
    per process via OnceLock (runtime state, so the intern cannot be const-
    folded), never inside the timed region.
  - The accessed token index is folded with the FFI input byte, so the intern
    cannot be hoisted.
  - The id a token receives is its first-appearance order in the stream, which is
    identical across every hash and load factor, so all four variants produce the
    byte-identical id sequence and the harness cross-validation catches a wrong
    variant.
  - The hit path does a real byte compare against the corpus bytes and the insert
    path does a real byte hash, so the measured cost is the genuine string-op-
    bound intern, not an integer-keyed table.

Axes:
  hash: FNV-1a vs an FxHash-style multiply-rotate. Both byte-walking.
  load factor: ~25% (CAP 16384) vs ~75% (CAP 5462). Non-power-of-two CAP is fine:
    `% CONST` is strength-reduced by LLVM to a reciprocal multiply, so both cells
    use the same probe arithmetic and the comparison isolates the load factor.
Baseline = intern_fnv_lf25.

Run: python3 gen_interner_intern.py && for v in intern_fnv_lf25 intern_fx_lf25 \
  intern_fnv_lf75 intern_fx_lf75; do (cd variants/$v && cargo build --release); done
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SIZES = [64, 256, 1024, 4096, 16384]
SEED = "0x5eed_1272_0503_0002"
# (load_tag, CAP, load_lo, load_hi): load band asserted in-code (percent).
LOADS = [("lf25", 16384, 24, 26), ("lf75", 5462, 74, 76)]
# (hash_tag, hash-fn body)
HASHES = [
    ("fnv", "let mut h: u64 = 0xcbf29ce484222325;\n    for &c in s {\n        h ^= c as u64;\n        h = h.wrapping_mul(0x100000001b3);\n    }\n    h"),
    ("fx", "let mut h: u64 = 0;\n    for &c in s {\n        h = (h.rotate_left(5) ^ c as u64).wrapping_mul(0x51_7c_c1_b7_27_22_0a_95);\n    }\n    h"),
]
BASELINE = "intern_fnv_lf25"

CARGO = """\
[workspace]
[package]
name = "{name}"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
name = "{name}"
path = "src/lib.rs"
crate-type = ["cdylib"]
[dependencies]
mockspace-bench-core = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev", features = ["std"] }}
mockspace-bench-macro = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev" }}
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
"""

LIB_TMPL = """\
// AUTO-GENERATED by gen_interner_intern.py. Intern-hot-path axis: hash = {htag},
// load factor = {ltag}. Every variant interns the identical token stream to the
// identical id sequence (id = first-appearance order, independent of hash and
// load factor), so the harness cross-validates byte-identical output. The corpus
// and access stream are built once per process via OnceLock; the accessed token
// index is folded with the FFI input byte so the intern cannot be hoisted.
use mockspace_bench_core::{{timed, FfiBenchCall}};
use mockspace_bench_macro::bench_variant;
use std::sync::OnceLock;

const DISTINCT: usize = 4096;
const ACCESS_LEN: usize = 8192;
const CAP: usize = {cap};
// the corpus size the finding names, plus the load-factor band this cell targets.
const _: () = assert!(DISTINCT == 4096 && ACCESS_LEN.is_power_of_two());
const _: () = assert!(DISTINCT * 100 >= CAP * {load_lo} && DISTINCT * 100 <= CAP * {load_hi});

struct Corpus {{
    blob: Vec<u8>,
    tok: Vec<(u32, u32)>, // (offset, len) into blob
}}
static CORPUS: OnceLock<Corpus> = OnceLock::new();
fn build_corpus() -> Corpus {{
    let mut blob: Vec<u8> = Vec::new();
    let mut tok = Vec::with_capacity(DISTINCT);
    let mut s: u64 = 1;
    for _ in 0..DISTINCT {{
        s = s.wrapping_mul(6364136223846793005).wrapping_add(1);
        let len = 3 + (s >> 40) as usize % 9; // 3..11 bytes, typical identifier length
        let off = blob.len() as u32;
        for _ in 0..len {{
            s = s.wrapping_mul(2862933555777941757).wrapping_add(1);
            blob.push(b'a' + (s >> 40) as u8 % 26);
        }}
        tok.push((off, len as u32));
    }}
    Corpus {{ blob, tok }}
}}

static ACCESS: OnceLock<Vec<u32>> = OnceLock::new();
fn build_access() -> Vec<u32> {{
    let mut v = Vec::with_capacity(ACCESS_LEN);
    let mut s: u64 = 7;
    for _ in 0..ACCESS_LEN {{
        s = s.wrapping_mul(6364136223846793005).wrapping_add(1);
        let r = s >> 33;
        // 70% of accesses hit the top-64 common tokens (the parse reality).
        v.push(if r % 10 < 7 {{ (r % 64) as u32 }} else {{ (r % DISTINCT as u64) as u32 }});
    }}
    v
}}

#[inline(always)]
fn hash(s: &[u8]) -> u64 {{
    {hash_body}
}}

#[bench_variant("{name}", sizes = [64, 256, 1024, 4096, 16384])]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    let corpus = CORPUS.get_or_init(build_corpus);
    let access = ACCESS.get_or_init(build_access);
    // slot -> corpus token index (u32::MAX = empty). Scratch, reset each call
    // outside the timed region, so the reset is not measured (matches the
    // original bench, which memset the table before its timer).
    let mut keys = vec![u32::MAX; CAP];
    let mut ids = vec![0u32; CAP];
    let mut next_id: u32 = 0;
    timed! {{ run {{
        let mut acc: u64 = 0;
        for (k, &b) in input.iter().enumerate() {{
            let ti = access[(k ^ b as usize) & (ACCESS_LEN - 1)] as usize;
            let (off, len) = corpus.tok[ti];
            let s = &corpus.blob[off as usize..off as usize + len as usize];
            let mut slot = (hash(s) % CAP as u64) as usize;
            let id = loop {{
                let occ = keys[slot];
                if occ == u32::MAX {{
                    keys[slot] = ti as u32;
                    ids[slot] = next_id;
                    let id = next_id;
                    next_id += 1;
                    break id;
                }}
                let (o2, l2) = corpus.tok[occ as usize];
                if &corpus.blob[o2 as usize..o2 as usize + l2 as usize] == s {{
                    break ids[slot]; // real byte-compare hit
                }}
                slot = (slot + 1) % CAP;
            }};
            acc ^= id as u64;
        }}
        output.copy_from_slice(&acc.to_le_bytes());
    }} }}
}}
"""


def variants():
    out = []
    for ltag, cap, lo, hi in LOADS:
        for htag, body in HASHES:
            out.append((f"intern_{htag}_{ltag}", htag, ltag, cap, lo, hi, body))
    return out


def write_variant(v):
    name, htag, ltag, cap, lo, hi, body = v
    d = os.path.join(HERE, "variants", name, "src")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(HERE, "variants", name, "Cargo.toml"), "w") as f:
        f.write(CARGO.format(name=name))
    lib = LIB_TMPL.format(
        name=name, htag=htag, ltag=ltag, cap=cap, load_lo=lo, load_hi=hi, hash_body=body
    )
    with open(os.path.join(d, "lib.rs"), "w") as f:
        f.write(lib)
    return name


def bench_section(names):
    paths = ", ".join(f'"variants/{n}/target/release/{n}"' for n in names)
    out = [
        "[bench.interner_intern]",
        'title = "Interner intern hot path: FNV vs FxHash x load factor 25% vs 75%"',
        'workload = "realistic"',
        f"master_seed = {SEED}",
        "[bench.interner_intern.normalise]",
        f'baseline = "{BASELINE}"',
        'mode = "subtract"',
    ]
    for n in SIZES:
        out.append("[[bench.interner_intern.sizes]]")
        out.append(f"n = {n}")
        out.append(f"variants = [{paths}]")
    return "\n".join(out) + "\n"


def main():
    vs = variants()
    names = [write_variant(v) for v in vs]
    frag_dir = os.path.join(HERE, "carrier_fragments")
    os.makedirs(frag_dir, exist_ok=True)
    frag = os.path.join(frag_dir, "resolve_interner_project.toml")
    marker = "# >>> interner_intern (generated)"
    prior = ""
    if os.path.exists(frag):
        prior = open(frag).read()
        if marker in prior:
            prior = prior.split(marker)[0].rstrip() + "\n"
    with open(frag, "w") as f:
        f.write(prior.rstrip() + ("\n\n" if prior.strip() else "") + marker + "\n" + bench_section(names))
    print("generated variants:", ", ".join(names))
    print("wrote [bench.interner_intern] to carrier_fragments/resolve_interner_project.toml")


if __name__ == "__main__":
    main()
