#!/usr/bin/env python3
"""Generate the carrier native-ceiling bench: the audit-fixed replacement for
the interp-vs-native-ceiling sketch that measured 1.2x because its program was a
comptime-visible constant the optimizer partially evaluated into native code
(comparing native to native). Here the program is a multiply-add chain that
crosses into every variant as wire bytes, so no variant can see it and fold it.
Three executions of the identical program: the switch interpreter, the
function-pointer-table interpreter, and a shape-specialized native loop that does
no per-node dispatch (what a compiler would emit for this program). All three
fold the same hash and cross-validate byte-exact; the interpreter/native ratio
is the honest dispatch-and-decode overhead. Giesen's corrected experiment put
this near 10x for compute-bound scalar code, not 1.2x.

Run: python3 gen_carrier_native_ceiling.py && for v in ceiling_native \
  ceiling_switch ceiling_fntable; do (cd variants/carrier_$v && cargo build \
  --release); done && cargo build --release && ./target/release/vehje-benches \
  carrier_native_ceiling
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SIZES = [64, 256, 1024, 4096, 16384]
SEED = "0x5eed_ce11_0000_0003"
BASELINE = "carrier_ceiling_native"
# (tag, imports fragment, results decl, exec expr)
VARIANTS = [
    ("native", "madd_bytes, native_madd, Decoded, REC24", "", "native_madd(&d, seed)"),
    ("switch", "madd_bytes, interpret, Decoded, REC24", "let mut results = vec![0u64; d.node_count];", "interpret(&d, seed, &mut results)"),
    ("fntable", "madd_bytes, interpret_fntable, Decoded, REC24", "let mut results = vec![0u64; d.node_count];", "interpret_fntable(&d, seed, &mut results)"),
]

CARGO = """\
[workspace]
[package]
name = "{name}"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
name = "{name}"
path = "src/lib.rs"
crate-type = ["cdylib"]
[dependencies]
mockspace-bench-core = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev", features = ["std"] }}
mockspace-bench-macro = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev" }}
vehje-bench-carrier = {{ path = "../../carrier" }}
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
"""

LIB = """\
// AUTO-GENERATED by gen_carrier_native_ceiling.py. Native-ceiling variant:
// {tag} execution of one madd-chain program (node_count ~ N). The program is
// built once from wire bytes and crosses FFI opaque, so this variant's optimizer
// cannot partially evaluate the interpretation, which is the defect that made
// the old ceiling read 1.2x. The native variant runs the chain with no per-node
// dispatch (compiled shape); the interp variants dispatch per node.
use mockspace_bench_core::{{timed, FfiBenchCall}};
use mockspace_bench_macro::bench_variant;
use std::sync::OnceLock;
use vehje_bench_carrier::{{{imports}}};

static BYTES: OnceLock<Vec<u8>> = OnceLock::new();
const ITERS: usize = 16;

#[bench_variant("{name}", sizes = [64, 256, 1024, 4096, 16384])]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    let bytes = BYTES.get_or_init(|| madd_bytes(N / 4, REC24));
    let d = Decoded::parse(bytes, REC24).unwrap();
    {results_decl}
    timed! {{ run {{
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < ITERS {{
            let seed = input[k % N] as u64 ^ (k as u64);
            acc ^= {exec};
            k += 1;
        }}
        output.copy_from_slice(&acc.to_le_bytes());
    }} }}
}}
"""


def main():
    names = []
    for tag, imports, rdecl, exec_expr in VARIANTS:
        name = f"carrier_ceiling_{tag}"
        names.append(name)
        d = os.path.join(HERE, "variants", name, "src")
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(HERE, "variants", name, "Cargo.toml"), "w") as f:
            f.write(CARGO.format(name=name))
        with open(os.path.join(d, "lib.rs"), "w") as f:
            f.write(LIB.format(name=name, tag=tag, imports=imports, results_decl=rdecl, exec=exec_expr))

    paths = ", ".join(f'"variants/{n}/target/release/{n}"' for n in names)
    out = [
        "[bench.carrier_native_ceiling]",
        'title = "Native ceiling: switch vs fn-table interp vs shape-specialized native, opaque program (carrier)"',
        'workload = "realistic"',
        f"master_seed = {SEED}",
        "[bench.carrier_native_ceiling.normalise]",
        f'baseline = "{BASELINE}"',
        'mode = "subtract"',
    ]
    for n in SIZES:
        out.append("[[bench.carrier_native_ceiling.sizes]]")
        out.append(f"n = {n}")
        out.append(f"variants = [{paths}]")
    section = "\n".join(out) + "\n"

    os.makedirs(os.path.join(HERE, "carrier_fragments"), exist_ok=True)
    with open(os.path.join(HERE, "carrier_fragments", "native_ceiling.toml"), "w") as f:
        f.write(section)
    print("generated variants:", ", ".join(names))
    print("wrote carrier_fragments/native_ceiling.toml")


if __name__ == "__main__":
    main()
