#!/usr/bin/env python3
"""Generate the closure / match-lowering / partial-eval bench cluster as
mockspace-harness variant cdylibs. This is the audit-fixed replacement for the
three standalone hand-timed Zig benches under closure-representation/,
match-lowering/, and partial-eval-specialization/ (which ran outside the harness
with hand-rolled clocks and hoistable, black_box-only-defended loops). Here each
alternative is a cdylib variant, state is built once via OnceLock, the FFI input
folds into the accumulator so nothing hoists, and same-result variants are
cross-validated to a byte-identical checksum by the harness.

Each variant crate is self-contained plain-std Rust with its own [workspace];
none depends on the carrier IR. Sections are written to
carrier_fragments/closure_match_pe.toml (bench.toml is NOT edited here).

Run: python3 gen_closure_match_pe.py && \
  for v in $(ls -d variants/closure_* variants/ml_* variants/pe_*); do \
    (cd "$v" && cargo build --release); done
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SIZES = "[64, 256, 1024, 4096, 16384]"

CARGO = """\
[workspace]
[package]
name = "NAME"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
name = "NAME"
path = "src/lib.rs"
crate-type = ["cdylib"]
[dependencies]
mockspace-bench-core = { git = "https://github.com/hiisi-digital/mockspace", branch = "dev", features = ["std"] }
mockspace-bench-macro = { git = "https://github.com/hiisi-digital/mockspace", branch = "dev" }
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
"""


def write_crate(name, lib_src):
    d = os.path.join(HERE, "variants", name, "src")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(HERE, "variants", name, "Cargo.toml"), "w") as f:
        f.write(CARGO.replace("NAME", name))
    with open(os.path.join(d, "lib.rs"), "w") as f:
        f.write(lib_src)


# ---------------------------------------------------------------------------
# Cluster 1: closure representation. Two usage patterns (sub-benches), each
# racing flat vs linked. The winner inverts between the patterns: create-once-
# call-many favours flat (O(1) capture access), create-many-call-once favours
# linked (O(1) pointer creation, no capture copy).
# ---------------------------------------------------------------------------

CLOSURE_HEAD = """\
// AUTO-GENERATED by gen_closure_match_pe.py. Closure representation cluster.
// DESC
// Cross-validated byte-for-byte against the sibling representation: both read
// the same capture values, so the accumulator is representation-independent.
// The FFI input drives the read index and folds into the accumulator, so the
// work cannot be hoisted.
use mockspace_bench_core::{timed, FfiBenchCall};
use mockspace_bench_macro::bench_variant;
use std::hint::black_box;
use std::sync::OnceLock;

const CAPS: usize = 8;
const REP: usize = 64;

static ENV: OnceLock<[i64; CAPS]> = OnceLock::new();
fn env() -> [i64; CAPS] {
    *ENV.get_or_init(|| {
        let mut e = [0i64; CAPS];
        let mut i = 0;
        while i < CAPS {
            e[i] = (i as i64) * 0x9E37 + 1;
            i += 1;
        }
        e
    })
}
"""

CLOSURE_CALL_MANY_FLAT = CLOSURE_HEAD.replace(
    "DESC",
    "Create-once-call-many, FLAT: captures are copied into flat storage once;\n"
    "// each of N*REP calls reads a slot by input-derived index (O(1) access).",
) + """
struct FlatClosure {
    caps: [i64; CAPS],
}

#[bench_variant("closure_call_many_flat", sizes = SIZES)]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {
    let clo = black_box(FlatClosure { caps: env() });
    let total = N * REP;
    timed! { run {
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < total {
            let seed = input[k % N] as u64 ^ (k as u64);
            let idx = (seed as usize) & (CAPS - 1);
            acc ^= clo.caps[idx] as u64 ^ seed;
            k += 1;
        }
        output.copy_from_slice(&acc.to_le_bytes());
    } }
}
""".replace("SIZES", SIZES)

CLOSURE_CALL_MANY_LINKED = CLOSURE_HEAD.replace(
    "DESC",
    "Create-once-call-many, LINKED: one closure points into a DEPTH-frame\n"
    "// environment chain; each call walks the chain to the root frame and reads\n"
    "// the slot (O(depth) access). Every frame carries the same captures, so a\n"
    "// full walk yields the same value the flat variant reads.",
) + """
const DEPTH: usize = 4;

struct Frame {
    slots: [i64; CAPS],
    parent: *const Frame,
}

#[bench_variant("closure_call_many_linked", sizes = SIZES)]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {
    let base = black_box(env());
    // stable DEPTH-frame chain; capacity reserved so the heap buffer never moves.
    let mut chain: Vec<Frame> =
        (0..DEPTH).map(|_| Frame { slots: base, parent: std::ptr::null() }).collect();
    let heap = chain.as_mut_ptr();
    let mut i = 1;
    while i < DEPTH {
        unsafe { (*heap.add(i)).parent = heap.add(i - 1) as *const Frame; }
        i += 1;
    }
    let leaf: *const Frame = black_box(unsafe { heap.add(DEPTH - 1) as *const Frame });
    let total = N * REP;
    timed! { run {
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < total {
            let seed = input[k % N] as u64 ^ (k as u64);
            let idx = (seed as usize) & (CAPS - 1);
            let mut e: *const Frame = leaf;
            unsafe {
                while !(*e).parent.is_null() {
                    e = (*e).parent;
                }
                acc ^= (*e).slots[idx] as u64 ^ seed;
            }
            k += 1;
        }
        // `chain` stays live to end of function, so `leaf` and the frame
        // pointers it walks remain valid through the whole timed loop.
        output.copy_from_slice(&acc.to_le_bytes());
    } }
}
""".replace("SIZES", SIZES)

CLOSURE_CREATE_MANY_FLAT = CLOSURE_HEAD.replace(
    "DESC",
    "Create-many-call-once, FLAT: each of N*REP iterations builds the parent\n"
    "// frame (ambient work, equal for both variants), then copies its CAPS values\n"
    "// into a fresh flat closure (the extra creation cost) and calls it once.",
) + """
struct FlatClosure {
    caps: [i64; CAPS],
}

#[bench_variant("closure_create_many_flat", sizes = SIZES)]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {
    let base = env();
    let total = N * REP;
    timed! { run {
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < total {
            let seed = input[k % N] as u64 ^ (k as u64);
            let idx = (seed as usize) & (CAPS - 1);
            // ambient parent frame (both variants pay this): frame[i] = base[i] ^ seed
            let mut frame = [0i64; CAPS];
            let mut i = 0;
            while i < CAPS {
                frame[i] = base[i] ^ (seed as i64);
                i += 1;
            }
            let frame = black_box(frame);
            // FLAT creation: copy the whole frame into the closure (the cost).
            let mut clo = FlatClosure { caps: [0i64; CAPS] };
            let mut j = 0;
            while j < CAPS {
                clo.caps[j] = frame[j];
                j += 1;
            }
            let clo = black_box(clo);
            acc ^= clo.caps[idx] as u64;
            k += 1;
        }
        output.copy_from_slice(&acc.to_le_bytes());
    } }
}
""".replace("SIZES", SIZES)

CLOSURE_CREATE_MANY_LINKED = CLOSURE_HEAD.replace(
    "DESC",
    "Create-many-call-once, LINKED: each of N*REP iterations builds the parent\n"
    "// frame (ambient work, equal for both variants), then creates the closure as\n"
    "// a single pointer to that frame (no capture copy) and calls it once.",
) + """
struct Frame {
    slots: [i64; CAPS],
}
struct LinkedClosure {
    parent: *const Frame,
}

#[bench_variant("closure_create_many_linked", sizes = SIZES)]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {
    let base = env();
    let total = N * REP;
    timed! { run {
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < total {
            let seed = input[k % N] as u64 ^ (k as u64);
            let idx = (seed as usize) & (CAPS - 1);
            // ambient parent frame (both variants pay this): frame[i] = base[i] ^ seed
            let mut slots = [0i64; CAPS];
            let mut i = 0;
            while i < CAPS {
                slots[i] = base[i] ^ (seed as i64);
                i += 1;
            }
            let frame = black_box(Frame { slots });
            // LINKED creation: just store a pointer to the frame (no copy).
            let clo = black_box(LinkedClosure { parent: &frame as *const Frame });
            acc ^= unsafe { (*clo.parent).slots[idx] } as u64;
            k += 1;
        }
        output.copy_from_slice(&acc.to_le_bytes());
    } }
}
""".replace("SIZES", SIZES)


# ---------------------------------------------------------------------------
# Cluster 2: match lowering. Four arm-selection strategies over arbitrary
# sparse keys, at several arm counts K and two hit distributions. All strategies
# return the same body for a given scrutinee, so they cross-validate.
# ---------------------------------------------------------------------------

MATCH_TMPL = """\
// AUTO-GENERATED by gen_closure_match_pe.py. Match-lowering cluster.
// __STRATLABEL__ arm selection, K=__K__ arms, __DIST__ hit distribution. arm keys are
// arbitrary and sparse (distinct low-12-bit slots so the jump table cannot
// collide); every strategy returns the same body for a given scrutinee, so the
// variants cross-validate byte-for-byte. The FFI input drives the scrutinee
// stream and folds into the accumulator, so nothing hoists.
// Each strategy uses a different projection of the shared Arms (jump table uses
// `dense`; the chains and tree use `keys`/`bodies`), so per-variant dead fields
// are expected.
#![allow(dead_code)]
use mockspace_bench_core::{timed, FfiBenchCall};
use mockspace_bench_macro::bench_variant;
use std::sync::OnceLock;

const K: usize = __K__;
const REP: usize = 64;
const HOT: usize = K - 1;

struct Arms {
    keys: [u64; K],
    bodies: [i64; K],
    dense: [i64; 4096],
}
static ARMS: OnceLock<Arms> = OnceLock::new();
fn arms() -> &'static Arms {
    ARMS.get_or_init(|| {
        let mut used = [false; 4096];
        let mut pairs: Vec<(u64, i64)> = Vec::with_capacity(K);
        let mut s: u64 = 999;
        let mut a = 0;
        while a < K {
            s = s.wrapping_mul(2862933555777941757).wrapping_add(3037000493);
            let mut slot = ((s >> 20) as usize) & 4095;
            while used[slot] {
                slot = (slot + 1) & 4095;
            }
            used[slot] = true;
            let high = (s >> 8) & 0xff;
            let key = high * 4096 + slot as u64;
            let body = ((s >> 5) & 0xffff) as i64;
            pairs.push((key, body));
            a += 1;
        }
        pairs.sort_by_key(|p| p.0);
        let mut keys = [0u64; K];
        let mut bodies = [0i64; K];
        let mut dense = [-1i64; 4096];
        let mut i = 0;
        while i < K {
            keys[i] = pairs[i].0;
            bodies[i] = pairs[i].1;
            dense[(pairs[i].0 & 4095) as usize] = pairs[i].1;
            i += 1;
        }
        Arms { keys, bodies, dense }
    })
}

#[inline(always)]
fn select_arm(seed: u64) -> usize {
    __ARM_SELECT__
}

#[inline(always)]
fn dispatch(tag: u64, a: &Arms) -> i64 {
    __STRATEGY__
}

#[bench_variant("__NAME__", sizes = SIZES)]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {
    let a = arms();
    let total = N * REP;
    timed! { run {
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < total {
            let seed = input[k % N] as u64 ^ (k as u64);
            let arm = select_arm(seed);
            let tag = a.keys[arm];
            acc ^= dispatch(tag, a) as u64 ^ seed;
            k += 1;
        }
        output.copy_from_slice(&acc.to_le_bytes());
    } }
}
""".replace("SIZES", SIZES)

ARM_UNIFORM = "((seed >> 33) as usize) % K"
ARM_HOT = "if (seed >> 40) % 10 != 0 { HOT } else { ((seed >> 33) as usize) % K }"

STRAT_IFCHAIN = """let mut i = 0;
    while i < K {
        if a.keys[i] == tag {
            return a.bodies[i];
        }
        i += 1;
    }
    -1"""
STRAT_HOTFIRST = """if a.keys[HOT] == tag {
        return a.bodies[HOT];
    }
    let mut i = 0;
    while i < K {
        if i != HOT && a.keys[i] == tag {
            return a.bodies[i];
        }
        i += 1;
    }
    -1"""
STRAT_JUMPTABLE = "a.dense[(tag & 4095) as usize]"
STRAT_TREE = """let mut lo = 0usize;
    let mut hi = K;
    while lo < hi {
        let mid = (lo + hi) / 2;
        let key = a.keys[mid];
        if key == tag {
            return a.bodies[mid];
        }
        if tag < key {
            hi = mid;
        } else {
            lo = mid + 1;
        }
    }
    -1"""

STRATS = {
    "ifchain": STRAT_IFCHAIN,
    "hotfirst": STRAT_HOTFIRST,
    "jumptable": STRAT_JUMPTABLE,
    "tree": STRAT_TREE,
}
STRAT_LABEL = {
    "ifchain": "linear if-chain (index order)",
    "hotfirst": "hot-first if-chain (hot arm tested first)",
    "jumptable": "jump table (masked O(1) index)",
    "tree": "binary decision tree (O(log K))",
}


def match_crate(strat, k, dist):
    name = "ml_%s_%s%d" % (strat, "u" if dist == "uniform" else "h", k)
    src = (
        MATCH_TMPL.replace("__STRATLABEL__", STRAT_LABEL[strat])
        .replace("__K__", str(k))
        .replace("__DIST__", dist)
        .replace("__ARM_SELECT__", ARM_UNIFORM if dist == "uniform" else ARM_HOT)
        .replace("__STRATEGY__", STRATS[strat])
        .replace("__NAME__", name)
    )
    return name, src


# ---------------------------------------------------------------------------
# Cluster 3: partial-eval specialization. A reduction metric (fold ratio =
# residual / original node count), NOT a strategy race. The timed pass walks the
# program folding whole-static subtrees; output carries an input-seeded checksum
# of the residual plus the live-node count. Two program shapes: a random
# static/dynamic mix (folds weakly) vs a block-structured template (folds
# strongly). Variants at different fractions/shapes may_differ.
# ---------------------------------------------------------------------------

PE_HEAD = """\
// AUTO-GENERATED by gen_closure_match_pe.py. Partial-eval cluster, SHAPE_DESC,
// static fraction __SF__%. REDUCTION bench: the timed pass walks the program
// folding whole-static subtrees to one constant; the fold ratio is
// residual/original node count. output carries an input-seeded checksum of the
// residual (so the pass cannot hoist) plus the live-node count in the high bits.
// The binding-time grade (here the node id) strictly decreases on every unfold,
// so the walk is well-founded and PE terminates.
use mockspace_bench_core::{timed, FfiBenchCall};
use mockspace_bench_macro::bench_variant;
use std::sync::OnceLock;

const SF: u64 = __SF__;
const REP: usize = 16;

#[derive(Clone, Copy)]
struct Node {
    op: u8,
    a: u32,
    b: u32,
    is_static: bool,
    val: i64,
}
// op: 0 = static literal, 1 = dynamic literal, 2 = add, 3 = mul, 4 = concat (dynamic)

struct Prog {
    nodes: Vec<Node>,
    root: u32,
    orig: u32,
}
static PROG: OnceLock<Prog> = OnceLock::new();

fn specialize(p: &Prog, seed: u64) -> (u32, u64) {
    let mut live: u32 = 0;
    let mut chk: u64 = seed ^ 0x9E3779B97F4A7C15;
    let mut stack: Vec<u32> = Vec::with_capacity(64);
    stack.push(p.root);
    while let Some(id) = stack.pop() {
        let n = p.nodes[id as usize];
        live += 1;
        if n.is_static {
            // whole static subtree folds to one constant; the value folds in the
            // seed so the residual is input-dependent (defeats hoisting).
            chk = chk.rotate_left(7)
                ^ (n.val as u64).wrapping_mul(0x100000001B3).wrapping_add(seed);
        } else {
            chk = chk.rotate_left(5) ^ (id as u64).wrapping_add(seed);
            match n.op {
                2 | 3 | 4 => {
                    // well-founded grade: children built before parent => smaller id.
                    debug_assert!(n.a < id);
                    stack.push(n.a);
                    if n.b != n.a {
                        debug_assert!(n.b < id);
                        stack.push(n.b);
                    }
                }
                _ => {}
            }
        }
    }
    (live, chk)
}
"""

PE_BUILD_RANDOM = """
fn build(n_leaves: usize, sf: u64) -> Prog {
    let mut nodes: Vec<Node> = Vec::new();
    let mut s: u64 = 0xABCDEF;
    let mut level: Vec<u32> = Vec::with_capacity(n_leaves);
    let mut i = 0;
    while i < n_leaves {
        s = s.wrapping_mul(6364136223846793005).wrapping_add(1);
        let r = s >> 33;
        let id = nodes.len() as u32;
        if r % 100 < sf {
            nodes.push(Node { op: 0, a: 0, b: 0, is_static: true, val: (r & 0xffff) as i64 });
        } else {
            nodes.push(Node { op: 1, a: 0, b: 0, is_static: false, val: 0 });
        }
        level.push(id);
        i += 1;
    }
    while level.len() > 1 {
        let mut next: Vec<u32> = Vec::with_capacity(level.len() / 2 + 1);
        let mut j = 0;
        while j < level.len() {
            if j + 1 < level.len() {
                let l = level[j];
                let rr = level[j + 1];
                let ls = nodes[l as usize].is_static;
                let rs = nodes[rr as usize].is_static;
                s = s.wrapping_mul(6364136223846793005).wrapping_add(1);
                let op = if (s >> 33) & 1 == 0 { 2u8 } else { 3u8 };
                let id = nodes.len() as u32;
                nodes.push(Node { op, a: l, b: rr, is_static: ls && rs, val: 0 });
                next.push(id);
                j += 2;
            } else {
                next.push(level[j]);
                j += 1;
            }
        }
        level = next;
    }
    let root = level[0];
    let orig = nodes.len() as u32;
    Prog { nodes, root, orig }
}
"""

PE_BUILD_STRUCTURED = """
fn build(n_blocks: usize, sf: u64) -> Prog {
    let mut nodes: Vec<Node> = Vec::new();
    let mut s: u64 = 0x13579;
    let mut acc: u32 = {
        let id = nodes.len() as u32;
        nodes.push(Node { op: 0, a: 0, b: 0, is_static: true, val: 0 });
        id
    };
    let mut bi = 0;
    while bi < n_blocks {
        s = s.wrapping_mul(6364136223846793005).wrapping_add(1);
        let r = s >> 33;
        let block: u32;
        if r % 100 < sf {
            // static block: an 8-node static add chain => whole subtree folds to 1.
            let mut sub: u32 = {
                let id = nodes.len() as u32;
                nodes.push(Node { op: 0, a: 0, b: 0, is_static: true, val: (r & 0xff) as i64 });
                id
            };
            let mut g = 0;
            while g < 7 {
                let lit = {
                    let id = nodes.len() as u32;
                    nodes.push(Node { op: 0, a: 0, b: 0, is_static: true, val: 3 });
                    id
                };
                let id = nodes.len() as u32;
                nodes.push(Node { op: 2, a: sub, b: lit, is_static: true, val: 0 });
                sub = id;
                g += 1;
            }
            block = sub;
        } else {
            let d = {
                let id = nodes.len() as u32;
                nodes.push(Node { op: 1, a: 0, b: 0, is_static: false, val: 0 });
                id
            };
            let id = nodes.len() as u32;
            nodes.push(Node { op: 4, a: d, b: d, is_static: false, val: 0 });
            block = id;
        }
        let id = nodes.len() as u32;
        nodes.push(Node { op: 4, a: acc, b: block, is_static: false, val: 0 });
        acc = id;
        bi += 1;
    }
    let orig = nodes.len() as u32;
    Prog { nodes, root: acc, orig }
}
"""

PE_RUN = """
#[bench_variant("__NAME__", sizes = SIZES)]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {
    let p = PROG.get_or_init(|| build(N, SF));
    let total = REP;
    timed! { run {
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < total {
            let seed = input[(k * 37) % N] as u64 ^ (k as u64);
            let (live, chk) = specialize(p, seed);
            // residual (live) and original node counts ride the high bits so the
            // fold ratio orig/live is recoverable from the recorded output.
            acc ^= chk ^ ((live as u64) << 40) ^ ((p.orig as u64) << 8);
            k += 1;
        }
        output.copy_from_slice(&acc.to_le_bytes());
    } }
}
""".replace("SIZES", SIZES)


def pe_crate(shape, sf):
    tag = "rand" if shape == "random" else "struct"
    name = "pe_%s_sf%d" % (tag, sf)
    shape_desc = (
        "random static/dynamic mix (reduction tree)"
        if shape == "random"
        else "block-structured template (static blocks + dynamic holes)"
    )
    build = PE_BUILD_RANDOM if shape == "random" else PE_BUILD_STRUCTURED
    src = (
        PE_HEAD.replace("SHAPE_DESC", shape_desc).replace("__SF__", str(sf))
        + build
        + PE_RUN.replace("__NAME__", name)
    )
    return name, src


# ---------------------------------------------------------------------------
# bench.toml fragment
# ---------------------------------------------------------------------------

def variant_path(name):
    return '"variants/%s/target/release/%s"' % (name, name)


def bench_section(bench, title, seed, variant_names, baseline=None, may_differ=False):
    out = ["[bench.%s]" % bench]
    out.append('title = "%s"' % title)
    out.append('workload = "realistic"')
    out.append("master_seed = %s" % seed)
    if may_differ:
        out.append("may_differ = true")
    if baseline is not None:
        out.append("[bench.%s.normalise]" % bench)
        out.append('baseline = "%s"' % baseline)
        out.append('mode = "subtract"')
    paths = ", ".join(variant_path(n) for n in variant_names)
    for n in [64, 256, 1024, 4096, 16384]:
        out.append("[[bench.%s.sizes]]" % bench)
        out.append("n = %d" % n)
        out.append("variants = [%s]" % paths)
    return "\n".join(out) + "\n"


def main():
    made = []
    sections = []

    # -- closures --
    write_crate("closure_call_many_flat", CLOSURE_CALL_MANY_FLAT)
    write_crate("closure_call_many_linked", CLOSURE_CALL_MANY_LINKED)
    write_crate("closure_create_many_flat", CLOSURE_CREATE_MANY_FLAT)
    write_crate("closure_create_many_linked", CLOSURE_CREATE_MANY_LINKED)
    made += [
        "closure_call_many_flat",
        "closure_call_many_linked",
        "closure_create_many_flat",
        "closure_create_many_linked",
    ]
    sections.append(
        bench_section(
            "closure_call_many",
            "Closure representation: create-once-call-many, flat vs linked (access cost dominates)",
            "0x5eed_c1a5_0000_0011",
            ["closure_call_many_flat", "closure_call_many_linked"],
            baseline="closure_call_many_flat",
        )
    )
    sections.append(
        bench_section(
            "closure_create_many",
            "Closure representation: create-many-call-once, flat vs linked (creation cost dominates)",
            "0x5eed_c1a5_0000_0012",
            ["closure_create_many_flat", "closure_create_many_linked"],
            baseline="closure_create_many_flat",
        )
    )

    # -- match lowering --
    match_seed = {
        (2, "uniform"): "0x5eed_3a7c_0000_0021",
        (8, "uniform"): "0x5eed_3a7c_0000_0022",
        (64, "uniform"): "0x5eed_3a7c_0000_0023",
        (64, "hot"): "0x5eed_3a7c_0000_0024",
    }
    # uniform benches: 3 strategies (hotfirst degenerates to ifchain under uniform).
    for k in (2, 8, 64):
        names = []
        for strat in ("ifchain", "jumptable", "tree"):
            nm, src = match_crate(strat, k, "uniform")
            write_crate(nm, src)
            names.append(nm)
            made.append(nm)
        sections.append(
            bench_section(
                "match_uniform_k%d" % k,
                "Match lowering: if-chain vs jump-table vs decision-tree, K=%d arms, uniform hits" % k,
                match_seed[(k, "uniform")],
                names,
                baseline="ml_jumptable_u%d" % k,
            )
        )
    # hot bench at K=64: all four strategies (hot-first if-chain is the point).
    names = []
    for strat in ("ifchain", "jumptable", "tree", "hotfirst"):
        nm, src = match_crate(strat, 64, "hot")
        write_crate(nm, src)
        names.append(nm)
        made.append(nm)
    sections.append(
        bench_section(
            "match_hot_k64",
            "Match lowering: hot-first if-chain vs the rest, K=64 arms, 90% hit one arm",
            match_seed[(64, "hot")],
            names,
            baseline="ml_jumptable_h64",
        )
    )

    # -- partial eval --
    for sf in (30, 50, 70, 90):
        nm, src = pe_crate("random", sf)
        write_crate(nm, src)
        made.append(nm)
    sections.append(
        bench_section(
            "pe_random",
            "Partial-eval specialization: fold ratio on a random static/dynamic mix (reduction metric)",
            "0x5eed_9ed3_0000_0031",
            ["pe_rand_sf30", "pe_rand_sf50", "pe_rand_sf70", "pe_rand_sf90"],
            may_differ=True,
        )
    )
    for sf in (50, 70, 90):
        nm, src = pe_crate("structured", sf)
        write_crate(nm, src)
        made.append(nm)
    sections.append(
        bench_section(
            "pe_structured",
            "Partial-eval specialization: fold ratio on a block-structured template (reduction metric)",
            "0x5eed_9ed3_0000_0032",
            ["pe_struct_sf50", "pe_struct_sf70", "pe_struct_sf90"],
            may_differ=True,
        )
    )

    frag = os.path.join(HERE, "carrier_fragments", "closure_match_pe.toml")
    header = (
        "# closure / match-lowering / partial-eval bench sections.\n"
        "# Generated by gen_closure_match_pe.py. Merge into bench.toml (the main\n"
        "# agent owns bench.toml; this fragment is not appended here).\n\n"
    )
    with open(frag, "w") as f:
        f.write(header + "\n".join(sections))
    print("generated %d variant crates:" % len(made))
    for n in made:
        print("  ", n)
    print("wrote fragment:", frag)


if __name__ == "__main__":
    main()
