#!/usr/bin/env python3
"""Generate the predecode bench: zero-copy wire decode versus a flat predecoded
form, both at op vocabulary 17. The reference interpreter decodes wire bytes
(offset math + from_le_bytes) on every node every iteration; a predecoded
interpreter transforms the program once into a flat 16-byte-record form (outside
the timed region, like parse) and then runs a tight switch with no wire
arithmetic. This measures whether the front-loaded predecode pays over the
per-call iteration count, and whether the smaller flat working set helps past L1.

Run AFTER gen_carrier_dispatch.py (it appends its own marker block at the end of
bench.toml). Order:
  python3 gen_carrier_predecode.py && \
  for v in carrier_predec_wire carrier_predec_flat; do \
    (cd variants/$v && cargo build --release); done && \
  cargo build --release && ./target/release/vehje-benches carrier_predecode
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SIZES = [64, 256, 1024, 4096, 16384]
SEED = "0x5eed_d15b_a7c4_0007"
VOCAB = 17
MARKER = "# >>> carrier_predecode (generated)"

CARGO = """\
[workspace]
[package]
name = "{name}"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
name = "{name}"
path = "src/lib.rs"
crate-type = ["cdylib"]
[dependencies]
mockspace-bench-core = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev", features = ["std"] }}
mockspace-bench-macro = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev" }}
vehje-bench-carrier = {{ path = "../../carrier"{carrier_features} }}
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
"""

# The wire variant decodes inside the timed loop (the shipped-default shape).
LIB_WIRE = """\
// AUTO-GENERATED by gen_carrier_predecode.py. Wire-decode baseline: the switch
// interpreter decoding operands from the byte stream on every node every
// iteration. The program crosses FFI as bytes.
use mockspace_bench_core::{{timed, FfiBenchCall}};
use mockspace_bench_macro::bench_variant;
use std::sync::OnceLock;
use vehje_bench_carrier::{{interpret, program_vocab, Decoded, REC24}};

static BYTES: OnceLock<Vec<u8>> = OnceLock::new();
const ITERS: usize = 16;

#[bench_variant("carrier_predec_wire", sizes = [64, 256, 1024, 4096, 16384])]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    let bytes = BYTES.get_or_init(|| program_vocab(N, {vocab}, REC24));
    let d = Decoded::parse(bytes, REC24).unwrap();
    let mut results = vec![0u64; d.node_count];
    timed! {{ run {{
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < ITERS {{
            acc ^= interpret(&d, input[k % N] as u64 ^ (k as u64), &mut results);
            k += 1;
        }}
        output.copy_from_slice(&acc.to_le_bytes());
    }} }}
}}
"""

# The flat variant predecodes once outside the timed loop, then interprets the
# flat form with no wire arithmetic. Same program bytes, same iteration count.
LIB_FLAT = """\
// AUTO-GENERATED by gen_carrier_predecode.py. Predecoded contender: transform
// the wire program into a flat 16-byte-record form once (outside the timed
// region, like parse), then run a tight switch with no wire arithmetic.
use mockspace_bench_core::{{timed, FfiBenchCall}};
use mockspace_bench_macro::bench_variant;
use std::sync::OnceLock;
use vehje_bench_carrier::predecode::{{predecode, interpret_predecoded}};
use vehje_bench_carrier::{{program_vocab, Decoded, REC24}};

static BYTES: OnceLock<Vec<u8>> = OnceLock::new();
const ITERS: usize = 16;

#[bench_variant("carrier_predec_flat", sizes = [64, 256, 1024, 4096, 16384])]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    let bytes = BYTES.get_or_init(|| program_vocab(N, {vocab}, REC24));
    let d = Decoded::parse(bytes, REC24).unwrap();
    let p = predecode(&d);
    let mut results = vec![0u64; d.node_count];
    timed! {{ run {{
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < ITERS {{
            acc ^= interpret_predecoded(&p, input[k % N] as u64 ^ (k as u64), &mut results);
            k += 1;
        }}
        output.copy_from_slice(&acc.to_le_bytes());
    }} }}
}}
"""


# The flat-threaded variant: preserve-none context-threaded dispatch over the
# flat predecoded form (A1 threaded shape + A2 flat form combined).
LIB_FLAT_THREADED = """\
// AUTO-GENERATED by gen_carrier_predecode.py. Flat + threaded: preserve-none
// context-threaded dispatch over the flat predecoded form.
use mockspace_bench_core::{{timed, FfiBenchCall}};
use mockspace_bench_macro::bench_variant;
use std::sync::OnceLock;
use vehje_bench_carrier::predecode::{{predecode, interpret_predecoded_threaded}};
use vehje_bench_carrier::{{program_vocab, Decoded, REC24}};

static BYTES: OnceLock<Vec<u8>> = OnceLock::new();
const ITERS: usize = 16;

#[bench_variant("carrier_predec_flatthread", sizes = [64, 256, 1024, 4096, 16384])]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    let bytes = BYTES.get_or_init(|| program_vocab(N, {vocab}, REC24));
    let d = Decoded::parse(bytes, REC24).unwrap();
    let p = predecode(&d);
    let mut results = vec![0u64; d.node_count];
    timed! {{ run {{
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < ITERS {{
            acc ^= interpret_predecoded_threaded(&p, input[k % N] as u64 ^ (k as u64), &mut results);
            k += 1;
        }}
        output.copy_from_slice(&acc.to_le_bytes());
    }} }}
}}
"""


def write_variant(name, lib, carrier_features=""):
    d = os.path.join(HERE, "variants", name, "src")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(HERE, "variants", name, "Cargo.toml"), "w") as f:
        f.write(CARGO.format(name=name, carrier_features=carrier_features))
    with open(os.path.join(d, "lib.rs"), "w") as f:
        f.write(lib.format(vocab=VOCAB))


def main():
    write_variant("carrier_predec_wire", LIB_WIRE)
    write_variant("carrier_predec_flat", LIB_FLAT)
    write_variant("carrier_predec_flatthread", LIB_FLAT_THREADED, ', features = ["threaded"]')
    names = ["carrier_predec_wire", "carrier_predec_flat", "carrier_predec_flatthread"]
    paths = ", ".join(f'"variants/{n}/target/release/{n}"' for n in names)
    lines = [
        "[bench.carrier_predecode]",
        'title = "Predecode: zero-copy wire decode vs flat predecoded form (carrier)"',
        'workload = "realistic"',
        f"master_seed = {SEED}",
        "[bench.carrier_predecode.normalise]",
        'baseline = "carrier_predec_wire"',
        'mode = "subtract"',
    ]
    for n in SIZES:
        lines.append("[[bench.carrier_predecode.sizes]]")
        lines.append(f"n = {n}")
        lines.append(f"variants = [{paths}]")
    section = "\n".join(lines) + "\n"

    toml_path = os.path.join(HERE, "bench.toml")
    with open(toml_path) as f:
        toml = f.read()
    if MARKER in toml:
        toml = toml.split(MARKER)[0].rstrip() + "\n"
    with open(toml_path, "w") as f:
        f.write(toml.rstrip() + "\n\n" + MARKER + "\n" + section)
    print("generated variants:", ", ".join(names))
    print("appended carrier_predecode to bench.toml")


if __name__ == "__main__":
    main()
