#!/usr/bin/env python3
"""Generate the C5 reachability benches: whole-column vs real semi-naive.

The audit found the old "delta" bench scanned the full edge list every round
(O(E) per round, only skipping non-dirty nodes), so it was not semi-naive at
all. This builds the honest comparison on the carrier's reach module (CSR
in-edge index + frontier worklist). Both strategies run over one shared graph
per shape and cross-validate byte-exact on the reach checksum, so the measured
gap is the evaluation strategy and nothing else.

Shapes (the crossover sweep the audit named): layered DAGs of depth 8, 32, 128
(deep => many rounds => semi-naive should win), a fan-in-heavy shallow graph
(one round => whole-column's simplicity may win), and a random DAG (middle
regime). The harness caps the graph at N=16384 nodes; the multi-million-node
magnitude goes to the scale-runner.

Run: python3 gen_carrier_reach.py && for v in <variants>; do
  (cd variants/$v && cargo build --release); done && cargo build --release
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SIZES = [64, 256, 1024, 4096, 16384]

# (bench, gen_expr with N and a per-shape seed). whole is the baseline.
SHAPES = [
    ("reach_chain8",  'let d = 8usize.min((N/4).max(2)); gen_layered(N, d, 3, 0x5eed_9008 ^ N as u64)'),
    ("reach_chain32", 'let d = 32usize.min((N/4).max(2)); gen_layered(N, d, 3, 0x5eed_9032 ^ N as u64)'),
    ("reach_chain128",'let d = 128usize.min((N/4).max(2)); gen_layered(N, d, 3, 0x5eed_9128 ^ N as u64)'),
    ("reach_fanin",   'let _=N; gen_fanin(N, 0)'),
    ("reach_randomdag",'gen_random_dag(N, 4, 0x5eed_9d00 ^ N as u64)'),
]
SEEDS = {
    "reach_chain8": "0x5eed_9eac_0000_0008",
    "reach_chain32": "0x5eed_9eac_0000_0032",
    "reach_chain128": "0x5eed_9eac_0000_0128",
    "reach_fanin": "0x5eed_9eac_0000_0f01",
    "reach_randomdag": "0x5eed_9eac_0000_0d00",
}

CARGO = """\
[workspace]
[package]
name = "{name}"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
name = "{name}"
path = "src/lib.rs"
crate-type = ["cdylib"]
[dependencies]
mockspace-bench-core = {{ git = "https://github.com/hiisi-digital/mockspace", rev = "49ff5f55b8413f7046281ae1944130c10509c361", features = ["std"] }}
mockspace-bench-macro = {{ git = "https://github.com/hiisi-digital/mockspace", rev = "49ff5f55b8413f7046281ae1944130c10509c361" }}
vehje-bench-carrier = {{ path = "../../carrier" }}
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
"""

LIB = """\
// AUTO-GENERATED by gen_carrier_reach.py. {bench} / {strategy}.
// The graph is built once per subprocess from a runtime seed (OnceLock), so the
// optimizer cannot fold it; the reach buffers are allocated once per run and
// reset in place, so the timed region allocates nothing. Each iteration seeds
// an input-derived perturb node so the computed fixpoint depends on the FFI
// input and cannot be hoisted. whole-column and semi-naive share the identical
// graph and marking, so they cross-validate byte-exact on the reach checksum.
use mockspace_bench_core::{{timed, FfiBenchCall}};
use mockspace_bench_macro::bench_variant;
use std::sync::OnceLock;
use vehje_bench_carrier::reach::{{
    gen_layered, gen_fanin, gen_random_dag, reset_reach, solve_whole, solve_semi, reach_checksum, Graph,
}};

static G: OnceLock<Graph> = OnceLock::new();
const ITERS: usize = 8;

#[bench_variant("{name}", sizes = [64, 256, 1024, 4096, 16384])]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    let g = G.get_or_init(|| {{ {gen_expr} }});
    let mut reach = vec![0u64; g.n];
{semi_decl}
    timed! {{ run {{
        let mut acc: u64 = 0;
        for k in 0..ITERS {{
            let perturb = input[k % N] as u64 ^ (k as u64);
            reset_reach(g, &mut reach, 64, perturb);
            {solve_call}
            acc ^= reach_checksum(&reach, perturb);
        }}
        output.copy_from_slice(&acc.to_le_bytes());
    }} }}
}}
"""

def main():
    frag_lines = []
    all_names = []
    for bench, gen_expr in SHAPES:
        variants = []
        for strategy in ("whole", "semi"):
            name = f"{bench.replace('reach_','r_')}_{strategy}"
            all_names.append(name)
            variants.append(name)
            if strategy == "semi":
                semi_decl = ("    let mut fr: Vec<u32> = Vec::with_capacity(g.n);\n"
                             "    let mut nx: Vec<u32> = Vec::with_capacity(g.n);\n"
                             "    let mut q = vec![false; g.n];")
                solve_call = "solve_semi(g, &mut reach, &mut fr, &mut nx, &mut q);"
            else:
                semi_decl = ""
                solve_call = "solve_whole(g, &mut reach);"
            d = os.path.join(HERE, "variants", name, "src")
            os.makedirs(d, exist_ok=True)
            with open(os.path.join(HERE, "variants", name, "Cargo.toml"), "w") as f:
                f.write(CARGO.format(name=name))
            with open(os.path.join(d, "lib.rs"), "w") as f:
                f.write(LIB.format(name=name, bench=bench, strategy=strategy,
                                   gen_expr=gen_expr, semi_decl=semi_decl, solve_call=solve_call))
        base = variants[0]  # whole
        paths = ", ".join(f'"variants/{v}/target/release/{v}"' for v in variants)
        frag_lines += [
            f"# >>> {bench} (generated)",
            f"[bench.{bench}]",
            f'title = "Reachability fixpoint: whole-column vs real semi-naive ({bench[6:]})"',
            'workload = "realistic"',
            f"master_seed = {SEEDS[bench]}",
            f"[bench.{bench}.normalise]",
            f'baseline = "{base}"',
            'mode = "subtract"',
        ]
        for n in SIZES:
            frag_lines += [f"[[bench.{bench}.sizes]]", f"n = {n}", f"variants = [{paths}]"]
        frag_lines.append("")
    os.makedirs(os.path.join(HERE, "carrier_fragments"), exist_ok=True)
    with open(os.path.join(HERE, "carrier_fragments", "reach.toml"), "w") as f:
        f.write("\n".join(frag_lines) + "\n")
    print("variants:", " ".join(all_names))
    print("wrote carrier_fragments/reach.toml")

if __name__ == "__main__":
    main()
