#!/usr/bin/env python3
"""Generate the carrier record-width bench: one variant cdylib per record
layout, all interpreting the same generated program, differing only in the
wire stride they decode. This is the audit-fixed replacement for the old
standalone record-width bench that (a) mislabeled its struct sizes and (b) ran
outside the harness with an empty CSV. Here the layouts are compile-time-
asserted in the carrier, the program crosses FFI as bytes, and the harness
cross-validates that every layout produces the identical checksum.

Layouts, and what each answers:
  rec12  4-byte header, 2 inline operands   (narrow; arity-3 nodes spill)
  rec16  4-byte header, 3 inline operands   (the true-16B-3-op contender never
                                             benched before, no pool, 4/line)
  rec20  8-byte header, 3 inline operands   (what the old "24B" actually was)
  rec24  8-byte header, 3 inline operands, 4 pad   (the baseline)
  rec32  8-byte header, 4 inline operands, 8 pad   (wide end)

Run: python3 gen_carrier_record_width.py && for v in carrier_rec12 carrier_rec16 \
  carrier_rec20 carrier_rec24 carrier_rec32; do (cd variants/$v && cargo build \
  --release); done && cargo build --release && ./target/release/vehje-benches \
  carrier_record_width
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
LAYOUTS = ["REC12", "REC16", "REC20", "REC24", "REC32"]
SIZES = [64, 256, 1024, 4096, 16384]
BASELINE = "carrier_rec24"
SEED = "0x5eed_ca55_e77e_0001"

CARGO = """\
[workspace]
[package]
name = "{name}"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
name = "{name}"
path = "src/lib.rs"
crate-type = ["cdylib"]
[dependencies]
mockspace-bench-core = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev", features = ["std"] }}
mockspace-bench-macro = {{ git = "https://github.com/hiisi-digital/mockspace", branch = "dev" }}
vehje-bench-carrier = {{ path = "../../carrier" }}
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
"""

LIB = """\
// AUTO-GENERATED by gen_carrier_record_width.py. Record-width axis variant:
// the program of N nodes is generated once (per process, per size) and encoded
// at the {layout} layout; the interpreter decodes at the same stride. node_count
// scales with the harness size N, so the size sweep walks the record array from
// L1-resident into memory, which is where record width starts to cost. The
// program crosses FFI as bytes, so the interpretation cannot be partially
// evaluated away.
use mockspace_bench_core::{{timed, FfiBenchCall}};
use mockspace_bench_macro::bench_variant;
use std::sync::OnceLock;
use vehje_bench_carrier::{{interpret, program_at, Decoded, {layout}}};

static BYTES: OnceLock<Vec<u8>> = OnceLock::new();
const ITERS: usize = 16;

#[bench_variant("{name}", sizes = [64, 256, 1024, 4096, 16384])]
fn run<const N: usize>(input: &[u8; N], output: &mut [u8; 8]) -> FfiBenchCall {{
    let bytes = BYTES.get_or_init(|| program_at(N, {layout}));
    let d = Decoded::parse(bytes, {layout}).unwrap();
    let mut results = vec![0u64; d.node_count];
    timed! {{ run {{
        let mut acc: u64 = 0;
        let mut k = 0usize;
        while k < ITERS {{
            acc ^= interpret(&d, input[k % N] as u64 ^ (k as u64), &mut results);
            k += 1;
        }}
        output.copy_from_slice(&acc.to_le_bytes());
    }} }}
}}
"""


def variant_name(layout: str) -> str:
    return "carrier_rec" + layout[3:]  # REC12 -> carrier_rec12


def write_variant(layout: str) -> str:
    name = variant_name(layout)
    d = os.path.join(HERE, "variants", name, "src")
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(HERE, "variants", name, "Cargo.toml"), "w") as f:
        f.write(CARGO.format(name=name))
    with open(os.path.join(d, "lib.rs"), "w") as f:
        f.write(LIB.format(name=name, layout=layout))
    return name


def bench_toml_section(names):
    paths = ", ".join(
        f'"variants/{n}/target/release/{n}"' for n in names
    )
    out = [
        "[bench.carrier_record_width]",
        'title = "Record width: wire-format stride and inline-vs-pool decode cost (carrier)"',
        'workload = "realistic"',
        f"master_seed = {SEED}",
        "[bench.carrier_record_width.normalise]",
        f'baseline = "{BASELINE}"',
        'mode = "subtract"',
    ]
    for n in SIZES:
        out.append("[[bench.carrier_record_width.sizes]]")
        out.append(f"n = {n}")
        out.append(f"variants = [{paths}]")
    return "\n".join(out) + "\n"


def main():
    names = [write_variant(l) for l in LAYOUTS]
    section = bench_toml_section(names)
    marker = "# >>> carrier_record_width (generated)"
    toml_path = os.path.join(HERE, "bench.toml")
    with open(toml_path) as f:
        toml = f.read()
    # Idempotent: strip any prior generated block, then append fresh.
    if marker in toml:
        toml = toml.split(marker)[0].rstrip() + "\n"
    with open(toml_path, "w") as f:
        f.write(toml.rstrip() + "\n\n" + marker + "\n" + section)
    print("generated variants:", ", ".join(names))
    print("appended [bench.carrier_record_width] to bench.toml")


if __name__ == "__main__":
    main()
