[package]
name = "vehje-runtime-gen"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
arvo.workspace = true
arvo-bits.workspace = true
arvo-hash.workspace = true
notko.workspace = true
vehje-ir.workspace = true
vehje-signature.workspace = true

[build-dependencies]
mockspace.workspace = true

[features]
default = []
