[workspace]
[package]
name = "br_lut_c_pred95"
version = "0.0.0"
edition = "2021"
publish = false
[lib]
name = "br_lut_c_pred95"
path = "src/lib.rs"
crate-type = ["cdylib"]
[dependencies]
mockspace-bench-core = { git = "https://github.com/hiisi-digital/mockspace", rev = "70fb75b500c8af22ddc18c5e0fb7d2467ab7dfc6", features = ["std"] }
mockspace-bench-macro = { git = "https://github.com/hiisi-digital/mockspace", rev = "70fb75b500c8af22ddc18c5e0fb7d2467ab7dfc6" }
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
